[connections.snowflake]
account = "comcomdataplatform.australia-east.azure"
user = "sam.wright@comcom.govt.nz"
role = "GRP_AZ_DA_PROD_INTEL_DEVELOPER"
warehouse = "DAP_WH_PROD_INTEL"
database = "DATAANALYTICS_DB_PRD"
schema = "INTEL_OUTPUT"
client_session_keep_alive = true
authenticator = "externalbrowser"

[connections.snowflake_TEST]
account = "comcomdataplatform.australia-east.azure"
user = "sam.wright@comcom.govt.nz"
role = "GRP_AZ_DA_NONPROD_INTEL_DEVELOPER"
warehouse = "DAP_WH_NONPROD_INTEL"
database = "DATAANALYTICS_DB_TST"
schema = "INTEL_OUTPUT"
client_session_keep_alive = true
authenticator = "externalbrowser"
 
[connections.snowflake_PROD]
account = "comcomdataplatform.australia-east.azure"
user = "sam.wright@comcom.govt.nz"
role = "GRP_AZ_DA_PROD_INTEL_DEVELOPER"
warehouse = "DAP_WH_PROD_INTEL"
database = "DATAANALYTICS_DB_PRD"
schema = "INTEL_OUTPUT"
client_session_keep_alive = true
authenticator = "externalbrowser"